### ISSUE TITLE
Delete roles on /unkusss

### ISSUE THREAD

**Issue by rechen-werk** [rechen-werk/Kilian#11]
**Is your feature request related to a problem? Please describe.**
Currently only the permissions are removed. This means that the guild still saves the channels if they are empty.

**Describe the solution you'd like**
Kilian should automatically remove channels if no one has permission to it any more and additionally they are empty. If they are not empty they should get moved to an archive. If someone joins again the channel should be retrieved from the archive again.

**Comment by xMuffin** [comment]
linked with #13

**Comment by xMuffin** [comment]
Already finished, will be available with archive
