### ISSUE TITLE
help command

### ISSUE THREAD

**Issue by MrMinemeet** [rechen-werk/Kilian#19]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem per se.
Most of the users are DAUs and don't know how to use the bot. That is the issue.

**Describe the solution you'd like**
A command `/help` that prints some useful information on how to use the bot. E.g., the `/kusss` command.
Maybe the bot should write a PN to new users, with some information that this command exists and so

**Comment by rechen-werk** [comment]
add a link to the repo here so one can read the documentation

**Comment by xMuffin** [comment]
or just list commands with short description?

**Comment by MrMinemeet** [comment]
In my opinion, listing the more frequently used commands with a brief description. In addition, a link to the docs for all commands then.
