### ISSUE TITLE
/ping overhaul

### ISSUE THREAD

**Issue by xMuffin** [rechen-werk/Kilian#23]
**Is your feature request related to a problem? Please describe.**
Not exactly, but fixes the 48h role limit.

**Describe the solution you'd like**
Instead of creating roles for each subject, just ping the channel with /ping #course.  
This would fix the problem of discord locking the bot and it gets rid of the gigantic wall of roles in server management.

**Comment by rechen-werk** [comment]
Yes, good idea!
But when a channel is "pinged"directly then the bot should not ping everyone any more, since this could happen out of context.
This is totally fine though.

**Comment by rechen-werk** [comment]
Just thought a bit more about it. This would break /join, because channels are not being suggested if you re not part of them.

**Comment by xMuffin** [comment]
truuueee frfr
