### ISSUE TITLE
Fancy Help

### ISSUE THREAD

**Issue by WieserJulian** [rechen-werk/Kilian#30]
I noticed that the help is a simple formated string. 
Would it be wanted to make it an fancy embeded Discord Help Menu with subhelps?

**Comment by WieserJulian** [comment]
I implemented an easy help and subcategory functionality. Is there something you want to add or another color?
<img width="535" alt="image" src="https://user-images.githubusercontent.com/97252196/225587174-19bde548-93e1-4e88-97e9-c25ab47b249a.png">

**Comment by rechen-werk** [comment]
Looks very good, but we would go for the color #701473 though. 
Please change this and create a PR :)
