### ISSUE TITLE
Multiple Generation of courses

### ISSUE THREAD

**Issue by rechen-werk** [rechen-werk/Kilian#9]
**Describe the bug**
If two or more persons use Kilians `/kusss`-Command at the same time, courses are generated multiple times.

**To Reproduce**
1. Get a partner
2. perform the kusss command at the same time

**Expected behavior**
All courses should be created once and everyone should be in every course

**Comment by BioGustav** [comment]
Try using a semaphore and check in the block if the course is still needed. [Related blog post](https://superfastpython.com/asyncio-semaphore/)
